apiVersion: skaffold/v2beta17
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: multi-author-blog/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: multi-author-blog/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: multi-author-blog/posts-comment
      context: postscomment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: multi-author-blog/qa
      context: qa
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
portForward:
  - resourceType: Service
    resourceName: auth-srv
    port: 4000
    localPort: 4000
  - resourceType: Service
    resourceName: posts-srv
    port: 4001
    localPort: 4001
  - resourceType: Service
    resourceName: posts-comment-srv
    port: 4002
    localPort: 4002
  - resourceType: Service
    resourceName: qa-srv
    port: 4003
    localPort: 4003
