apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-storage-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
