apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-storage-pv
spec:
  storageClassName: nats-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nats-data"
